//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datatable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regalos
    {
        public int Id_regalo { get; set; }
        public string Regalo { get; set; }
        public string Entregado { get; set; }
    }
}
